server:
  port: 8087
  servlet:
    context-path: /media-process
  tomcat:
    threads:
      max: 2

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:appdb
    driverClassName: org.h2.Driver
    username: sa
    password: anypass
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  liquibase:
#    change-log: classpath:database/schema.sql
#  jmx:
#    enabled: true
  batch:
    job:
      enabled: false
#    hadoop:
#      fsUri: hdfs://borneo:8020
#      resourceManagerHost: borneo